name: Minimizing CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout repo
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/github-push
      - name: Git checkout master
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Create minimized files
        run: |
          npm ci
          npm run build

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "CI: Automated min build push" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
